spring.application.name=backend-server

# Oracle Database
spring.datasource.url=${DATASOURCE_URL:jdbc:oracle:thin:@//oracle.fiap.com.br:1521/orcl}
spring.datasource.username=${DATASOURCE_USERNAME:rm561928}
spring.datasource.password=${DATASOURCE_PASSWORD:100107}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

# JWT
api.security.token.secret=${JWT_SECRET:starforge-jwt-secret-key-muito-segura-2026-gs-fiap}
api.security.token.expiration=86400000

# Server
server.port=8080

# Springdoc/Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
